name: idpi_dev
channels:
- conda-forge
dependencies:
- pytest>=7.1.1
- cfgrib>=0.9.10.1
- jinja2>=3.1.1
- netcdf4>=1.5.8
- black>=22.3.0
- darglint>=1.8.1
- pre-commit>=2.18.1
- flake8>=3.8.4
- flake8-bugbear>=22.3.23
- flake8-builtins>=1.5.3
- flake8-docstrings>=1.6.0
- flake8-eradicate>=1.2.0
- flake8-mutable>=1.2.0
- flake8-rst-docstrings>=0.2.5
- isort>=5.10.1
- mypy>=0.942
