name: Jake Github Action

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: python:3.8-slim-buster
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: get dependencies
      run: |
        conda env create --file environment_dev.yml
        conda activate idpi_env
        conda list > packages.list
    - name: Run Jake
      uses: sonatype-nexus-community/jake-github-action@main
      with:
        packagesListFile: environment_dev.yml
